name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # (a) Version Control Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # (b) Dependency Installation
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (c) Testing and Validation
      - name: Run tests
        run: |
          pytest

